### ISSUE TITLE
Built In Extractor

### ISSUE THREAD

**Issue by edsimpsons83** [yattee/yattee#165]
It would be nice to have a build in extractor for better performance so we don't have to use Invidious. This is what FreeTube is using.

"FreeTube uses a built in extractor to grab and serve data / videos. The [Invidious API](https://github.com/iv-org/invidious) can also optionally be used. FreeTube does not use any official APIs to obtain data. While YouTube can still see your video requests, it can no longer track you using cookies or JavaScript. Your subscriptions and history are stored locally on your computer and never sent out."

**Comment by DEFCON001** [comment]
Local subscription, history and playlists would be cool, but it would probably be a big feature, and would take some time to develop. Fingers crossed it eventually happens though.

**Comment by aneverhopefulhelper** [comment]
What with google/youtube now blocking the IP addresses of piped and invidious instances, might this be a serious consideration instead of relying on them? Since, for the foreseeable future, at least it seems most public invidious and piped instances are going to be blocked and thus this renders Yattee inoperable for watching youtube videos.

This would be a nice backup or a better plan than always relying on something blocked so easily.

**Comment by stonerl** [comment]
Since Newpipe is facing the same issues, [see here](https://github.com/TeamNewPipe/NewPipe/issues/11139), I don't think having another extractor maintained solves any of the underlying problems.

**Comment by aneverhopefulhelper** [comment]
Fair, although FreeTube appears to be working for now.

**Comment by stonerl** [comment]
I'm going to close this one. Since I don't think this is the focus for Yattee.

**Comment by aneverhopefulhelper** [comment]
That's a shame because it really is frustrating having to press retry 500+ times sometimes just to get a video to load (if it does at all).

**Comment by stonerl** [comment]
@aneverhopefulhelper PR #810 might help you with that
