### ISSUE TITLE
New player component for 4K and better controls: mpv?

### ISSUE THREAD

**Issue by Deagan** [yattee/yattee#33]
I understand the limitations of the iOS native video player, but I didn't see a request for it here. The VLC player solution seems like a good proposition, hopefully it can be implemented.

4K video quality with working playback speed adjustment on my Apple TV and iPad would be perfect!

**Comment by arekf** [comment]
Replacing `AVPlayer` with `VLCKit` will give better support for other stream formats (including DASH) and higher resolutions. It will require designing new player controls UI.

This is the next thing I planned to work on. Thanks for creating an issue.

**Comment by arekf** [comment]
I've tried with `VLCKit`, but unfortunately, support for playing separate video and audio streams is experimental and very buggy, it is impossible to seek through the video at all 😞 

My plan now is to try with [mpv](https://github.com/mpv-player/mpv), but this will require much more work. It needs to be manually compiled for all the platforms which might not be the easiest.

I am open to other ideas and any help with this.

**Comment by FireMasterK** [comment]
Have you tried playing via DASH if that's possible?

**Comment by arekf** [comment]
> Have you tried playing via DASH if that's possible?

Is DASH available for all videos? I get empty field in the response of Piped API for most I tried 😕

**Comment by FireMasterK** [comment]
You're actually supposed to create your own manifest. However, when the dash field is present in the API, you should prefer to use that instead of creating your own. The reasoning is that you will only see the dash field in OTF streams - this is the only time where youtube provides such manifest.

In the official frontend, it's done here: https://github.com/TeamPiped/Piped/blob/83411158c7e377e51befa90eb66ec6e27c18e3e5/src/components/Player.vue#L221-L224 and https://github.com/TeamPiped/Piped/blob/master/src/utils/DashUtils.js

**Comment by arekf** [comment]
Thanks, I tried with VLC desktop app to be sure it's not me misusing the library but looks like DASH is also handled poorly, same problems with seeking through the video.

**Comment by heilerich** [comment]
Maybe google‘s own [google/shaka-player-embedded](https://github.com/google/shaka-player-embedded) would be a solution? It is explicitly built for playing DASH. I have never used it personally, so no idea how well it works. The [basic integration tutorial](https://google.github.io/shaka-player-embedded/md_shaka_docs_tutorial_setup.html) seems pretty straightforward, though. It might be worth a try.

**Comment by arekf** [comment]
> Maybe google‘s own [google/shaka-player-embedded](https://github.com/google/shaka-player-embedded) would be a solution? It is explicitly built for playing DASH. I have never used it personally, so no idea how well it works. The [basic integration tutorial](https://google.github.io/shaka-player-embedded/md_shaka_docs_tutorial_setup.html) seems pretty straightforward, though. It might be worth a try.

Thanks for recommendation, but unfortunately Shaka Player is only for iOS, there's no way to build for Apple TV or Mac.

I think mpv is only reliable option left to go.

**Comment by arekf** [comment]
https://github.com/yattee/yattee/releases/tag/v1.4-alpha.1 

This build contains new player built on MPV, for those who want to have a look.

**Comment by Deagan** [comment]
> https://github.com/yattee/yattee/releases/tag/v1.4-alpha.1
> 
> This build contains new player built on MPV, for those who want to have a look.

Awesome! The new changes look great, but unfortunately, it seems that the app is only playing audio, no video (see screenshot)? I used Signulous to sideload on my iPhone 13 Pro Max on 15.1.1, and I'm unsure if this requires anything else to be installed/setup.

![3EB31878-4C26-48AC-91EA-605D32F1B178](https://user-images.githubusercontent.com/19179570/159348644-11fa506d-4586-4f80-b252-949e36f08add.jpeg)

Thank you for your hard work!
Deagan

**Comment by arekf** [comment]
> The new changes look great, but unfortunately, it seems that the app is only playing audio, no video (see screenshot)?
> 
> I used Signulous to sideload on my iPhone 13 Pro Max on 15.1.1, and I'm unsure if this requires anything else to be installed/setup.

Looks like you've found a bug, I was able to reproduce with simulator. I will try to fix in next build. #78

**Comment by stripedgoat** [comment]
Hello, thank you very much for your hard work 🙏🏼 The new player is a whole lot better than the previously used, built-in iOS player. The issue of constantly poor playback quality is no longer present, and the player keeps playing the media at at steady 1080p. During the use of the 1.4 alpha, I've encountered a few bugs (which is ofcourse normal for an alpha release), so I'd like to report them. I'm not sure if they should rather be reported separately or not, but I'll write them together for now.

**App version:** 1.4 Alpha
**iOS version:** 15.4
**iDevice:** iPhone Xs
**Sideloaded with:** Sideloadly v0.25.1

**Bug #1:** Display keeps dimming and thus turning off during playback, even when the video is fullscreened. The home bar is also constantly present even in fullscreened playback.

**Bug #2:** With the option "Pause when player is closed" disabled, when I minimize the playback, and then long-press the mini player to close the video, the playback doesn't stop in the background. This isn't an existing issue with the stable release.

**Bug #3:** Removing a video from a playlist does actually remove it as it should, but it requires you to re-open the app in order to see it removed from the playlist. You can't see the instant visual change (video disappearing from the list) when you hit the option to remove the video.

**Bug #4:** Sometimes the video starts to heavily lag, the trigger for it being especially if I pick a playback quality manually during playback.

These are the bugs I noticed the most.

**Additional welcome features would be:**

1. Add a toggle in the Settings "Close the player after playback is finished". This is currently the default behavior: Once the video reached the end, the player closes automatically. It would be nice if we could keep the player open even if the playback ends, as I often like to read comments once the playback finished. Currently I have to re-open the video and pause it.
2. Another toggle to Disable/Enable the Queue function. I only want to play the actual video I choose to play, and often I have to clean the Queue from videos I didn't finish watching, else they would continue playing once the current video reaches to the end.

**Comment by arekf** [comment]
@Deagan I've just published another alpha build which should partially resolve the problem - video should play properly in portrait, but breaks again when going fullscreen. Could you confirm this is the same with physical device? I don't have any Max device to test and I'm using simulator.

@stripedgoat thanks for bug reports and feature ideas. I've opened them as separate issues.

**Comment by Deagan** [comment]
> @Deagan I've just published another alpha build which should partially resolve the problem - video should play properly in portrait, but breaks again when going fullscreen.

Thanks for the update! Installing v1.3.3 with Signulous, it seems that it doesn't show options for 4K any longer? It selects "Adaptive" even though "Best Quality Available" is set.

![69FB63D1-6E9E-41A2-BF7D-5E781C08B823](https://user-images.githubusercontent.com/19179570/160304979-cee47cf2-89e4-4270-9d0e-30708b4af8bb.png)

Was there a fallback to the old video player, in case MPV doesn't work properly? If so, perhaps that is what is happening here?

A fallback would be a good implementation, in cases where the video malfunctions somehow!

**Comment by arekf** [comment]
@Deagan you need to install [1.4-alpha.2](https://github.com/yattee/yattee/releases/tag/v1.4-alpha.2), this was released today along stable release of 1.3.3

For the fallback - the old player stays and there even will be ability to switch between them during playing. In fact you can try it now by tapping "MPV" in the status bar which should change to "AVPlayer".

**Comment by Deagan** [comment]
> @Deagan you need to install [1.4-alpha.2](https://github.com/yattee/yattee/releases/tag/v1.4-alpha.2), this was released today along stable release of 1.3.3

Apologies, I forgot we were using an Alpha branch!

I have installed v1.4a2, and the video is working!

![BD68AB30-BEF5-4DDB-A86E-7EE4903C19B7](https://user-images.githubusercontent.com/19179570/160305646-dc845f9d-819b-4fa1-b746-e76778cb4457.png)

I am also able to switch between the two players by tapping the player title successfully!

Though now it seems that that the MPV player has issues displaying a smooth frame rate, regardless of resolution. From 4K to 720p, while using MPV, it seems that the video is dropping frames, likely at a frame rate of like 15fps or so, making the video look quite juttery.

The aforementioned fullscreen bug is also present on my iPhone 13 Pro Max. The MPV video's audio continues to play, but the video itself goes black. If I exit fullscreen mode, minimize the video, and then put it in focus again, it seems to reinitialize the video, and it can play normally again!

**Comment by arekf** [comment]
@Deagan a new build has been released, I'd appreciate checking if the issue got fixed.

**Comment by Deagan** [comment]
@arekf Yay, fullscreen works great with MPV now!
![6B15EFB8-2073-4289-9948-3EE279517861](https://user-images.githubusercontent.com/19179570/161464451-f39c7422-bdaf-4904-8754-34845e2d76ee.jpeg)

It seems that the video is still dropping some frames on my iPhone 13 Pro Max. Was there any way to add a "Stats for Nerds" OSD and/or frame rate counter?

Watching a 4K60FPS Linus Tech Tips video may be taxing on the system, but perhaps performance can be optimized somehow?

It seems to go from smooth video, to choppy, to smooth, but I'm unsure what frame rate it is actually playing at and whether or not it was due to video buffering or actual playback performance.

**Comment by Deagan** [comment]
I have found another bug where the video goes black when using Auto-Rotate for video orientation.

Here is a video recording for reference:


As the video begins playing, you can see that the frame rate is choppy, then becomes a bit smoother.

At around 18 seconds, I show that fullscreen mode works normally using the Fullscreen Button. Here, you can see that playback performance becomes choppy again.

At around 38 seconds, I minimize from fullscreen mode using the Fullscreen Button, then attempt to use Auto-Rotate around 59 seconds (video goes black).

Thanks again for all your hard work!
