### ISSUE TITLE
Vevo music videos fail to load using Invidious

### ISSUE THREAD

**Issue by ghost** [yattee/yattee#457]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Some videos (mostly music, and especially Vevo videos) fail to load in the Yattee iOS app using Invidious.

### Expected Behavior

Videos should load.

### Device & OS Version

iPhone, iOS 16.5

### App Build

142

**Comment by 34candos** [comment]
Note: when the player is set to "AVPlayer XXXX HLS, Stream", the error is  "Failed loading video. Cannot Open"; when the player is set to "MPV XXX - Any format", the error becomes "Error while opening file".

**Comment by Umpaaa** [comment]
This isn't a Yattee bug, it's an [issue](https://github.com/iv-org/invidious/issues/3822) when using some Invidious instances (no issues with Piped). It seems to be caused by google blocking ips, to certain videos, so maybe try changing your ip or disable/enable proxy videos for the invidious instance. If you're maintaining your own instance you can try [this](https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621).
