### ISSUE TITLE
"Connection Failed" While Signing Into Piped Account

### ISSUE THREAD

**Issue by ghost** [yattee/yattee#474]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

As indicated in #67, I am having the same issue now.
Here is what I do:
1.     created an account on a piped instance
2.     added the instance as a location in Yattee (using api address)
3.     in the location, gave the frontend url and entered credentials.
4.     connection failed
Am I missing something?
Connecting using an Invidious account works.

### Expected Behavior

Piped Account should be added.

### Device & OS Version

iOS 16

### App Build

148

**Comment by hnk** [comment]
Okay, I had the same issue for a minute, but I think this may be a UI/UX issue with piped, and not yattee.

When opening an instance of piped, you have to select "Preferences" and scroll down to the "Instance" section and select your current instance. The "official" instance seems to be pre-selected. If you do not do this and click to register, the account is created on the "official" instance and not the local one you are browsing on.

When you then try to add the instance in yattee, the login fails, because the account was created on another instance.

**Comment by sallyFoster** [comment]
@hnk Are we able to sign in on other instances?

**Comment by stonerl** [comment]
Is this still an issue? That seems more like a problem with the instance rather than Yattee.

@sallyFoster You need credentials for every instance you want to use. You cannot use one for all.

**Comment by sallyFoster** [comment]
@stonerl Yeah, I am able to sign in now.
