### ISSUE TITLE
[Issue] Unable to play playlists

### ISSUE THREAD

**Issue by CanIHelp101** [yattee/yattee#57]
Clicking on a playlist simply shows a blank screen. Tried on both versions 1.3 & 1.3.1. Proof: https://imgur.com/a/C3wJTNy

**Comment by Rbot427** [comment]
Hello,

I believe this issue is somehow connected to the "Save history of searches, channels, and playlists" setting for history. When I uncheck this setting, playlists no longer load as demonstrated by @CanIHelp101 . However, with this setting enabled, I can load playlists just fine. 

@CanIHelp101 do you have this setting enabled?

**Comment by CanIHelp101** [comment]
@Rbot427 I have it disabled. You're right. Turning on "Save history of searches, channels, and playlists" in settings makes the playlists show.
