### ISSUE TITLE
Video not scrubbing

### ISSUE THREAD

**Issue by ooosssay** [yattee/yattee#626]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

When scrubbing it does nothing at all and the video just continues to play.

### Expected Behavior

To go to the time I scrubbed to.

### Device & OS Version

iPhone, iOS 17.2.1

### App Build

180

### Screenshots, Videos and other files

[yattee-180-mpv-log.txt](https://github.com/yattee/yattee/files/14488862/yattee-180-mpv-log.txt)

https://github.com/yattee/yattee/assets/129241633/b752f3ad-f73c-4abc-baf1-2fcf6ce6dfa2

**Comment by stonerl** [comment]
I noticed this as well. But it only seems to happen with Piped. Not with Invidious, though.

**Comment by ooosssay** [comment]
This is true as when I was using the video I was using a piped instance.

**Comment by stonerl** [comment]
@ooosssay Can you switch to a different codec? I think the problem only appears is with mp4.

**Comment by ooosssay** [comment]
While I was testing this, stream was working fine but when I tried the other codecs they will stop loading when at a new timestamp or freeze the frame with audio still playing (might be the server)

**Comment by stonerl** [comment]
Yeah, it is better when using WebM over MP4 it seems, but still has some issues. Especially when scrubbing too far outside the current buffer.

HLS or Stream is the way to go. I'll try to implement the missing features like captions and playback speed in AVPlayer, since it supports HLS and HLS is preferable over Stream IMHO.

**Comment by stonerl** [comment]
Did some digging. The problem is unrelated to the codec used. It seems more an issue with Piped. When scrubbing or jumping forward, Yattee requests new segments of the video, and it seems it that requesting these segments takes up a long time. Every so often, one has to wait up to a minute for the correct segment to be found. Then the playback continues.
