### ISSUE TITLE
Could not load video - no supported streams available

### ISSUE THREAD

**Issue by saukkico** [yattee/yattee#804]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

I’ve seen this error quite a many times lately. Trying to open a video, but it doesn’t play. On Apple tv there’s not even a error message. Instead it just appears to be loading. 
in some cases switching from MPV to AVplayer solves the problem, but not allways. 
Here’s one example: https://www.youtube.com/watch?v=apdZ7xmytiQ
I can play that video on my Invidious instance, but Yattee connected to the same instance can’t play it. 

### Expected Behavior

The video starts to play

### Device & OS Version

Latest iOS, latest tvOS

### App Build

195

### Screenshots, Videos and other files

![IMG_1442](https://github.com/user-attachments/assets/d59cfb6e-e3fd-48df-af06-e9fb8af15ef9)

**Comment by stonerl** [comment]
Restore the default quality profiles and try again.

![image](https://github.com/user-attachments/assets/b0a4b46b-429e-411d-a635-f51629579581)

**Comment by saukkico** [comment]
Thanks! That seems to solve the problem for that video. But here's another example which is not working even after I reset the quality profiles. 

https://www.youtube.com/watch?v=3q8QT-9gJs4

Yesterday I was able to play that video with AVplayer, but it doesn't seem to work now. It just appears to be loading, but nothing happens. 

![image](https://github.com/user-attachments/assets/5c7142f8-c7ee-45dc-8919-65c61dd2f630)

Invidious can play the video.

**Comment by retrocaster** [comment]
I can confirm that I see the same issue with that "Modernizing my 35 year old..." video:
- it plays fine in the web interface of my local invidious instance
- if I try on my Apple TV 3rd gen running Yattee 1.5.2 (build 195) it just does an endless loading message

My default profile is "MPV - 1440p, 60fs, any format" and it's trying to load a 1440p WebM version

**Comment by stonerl** [comment]
That could be an issue with the instance your using. The Linus Tech Tips video does load for me. But the "Modernizing my 35 year old…" does not.

Need to do some testing.

**Comment by stonerl** [comment]
Hmm, not an instance issue. The function that is selecting the best stream for playback does not receive any streams.

**Comment by saukkico** [comment]
Here's few other videos I've found not working on Yattee:


https://www.youtube.com/watch?v=GzRqplxQ2WQ

https://www.youtube.com/watch?v=Niaw3Ez0YLU

**Comment by stonerl** [comment]
> https://www.youtube.com/watch?v=GzRqplxQ2WQ
>
That one has a different cause. It seems to be age restricted.

**Comment by AndrzejStecyk** [comment]
Hi everyone! Just wanted to chime in—I’m also having trouble with Linus Tech Tips videos; they aren’t working for me either. I could list plenty of examples, but I ran an experiment instead. I set up Piped in my own setup, and with Piped as the backend, most videos load fine (though it has its own quirks). So, I’m starting to think this might be a configuration issue with Invidious or possibly the integration between Invidious and Yattee.

To the Yattee devs: is there anything I can do to help track down the root cause? I’m currently working as a reliability engineer in IT and have a testing background. I’m not into app dev just yet, but I’m more than willing to dive in with some guidance!
